### ISSUE TITLE
Add new debug action `destroy <item>`

### ISSUE THREAD

**Issue by EpocDotFr** [EpocDotFr/yatage#11]
Destroy an item in the inventory

**Comment by EpocDotFr** [comment]
Because it's still under heavy development

**Comment by AjayAntoIsDev** [comment]
Shall i add it?

**Comment by EpocDotFr** [comment]
No

**Comment by AjayAntoIsDev** [comment]
Why.

**Comment by EpocDotFr** [comment]
Please stop that now. Are you reading all my comments?

**Comment by AjayAntoIsDev** [comment]
Well okay idk whats under "heavy development" the command works fine when i added it
